
dataset:
  id:
    name: Tumor
    root: /mnt/homeGPU/isevillano/Github/GleasonMap/Data/TrainTest
    split: val
    loader: classification

  ood:
    - name: FAR_OOD
      root: 
      loader: classification

    - name: NEAR_OOD
      root: 
      loader: classification

network:
  name: swin
  model: openood/networks/swin_t.py
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: True
  num_gpus: '@{num_gpus}'

ood:
  method: energy
  temperature: 1.0

trainer:
  name: train
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.0005
    num_epochs: 50
  batch_size: 64
  
evaluation:
  batch_size: 64
  device: cuda:0
  metrics:
    - AUROC
    - FPR95
    - FAR_OOD

seed: 42