
num_gpus: 1
num_workers: 4
seed: 42

output_dir: /mnt/homeGPU/jmartin/entorno_jose/results/tumor_resnet50

dataset:
  name: Tumor
  root: /mnt/homeGPU/isevillano/Github/GleasonMap/Data/TrainTest
  num_classes: 14       
  image_size: 224 
  interpolation: bilinear
  normalization_type: imagenet
  num_gpus: '@{num_gpus}'
  num_workers: '@{num_workers}'
  split_names: [train, val]

  train:
    dataset_class: FolderDataset
    data_dir: /mnt/homeGPU/isevillano/Github/GleasonMap/Data/TrainTest/train
    batch_size: 64
    shuffle: True

  val:
    dataset_class: FolderDataset
    data_dir: /mnt/homeGPU/isevillano/Github/GleasonMap/Data/TrainTest/val
    batch_size: 64
    shuffle: False

  

network:
  name: resnet50
  num_classes: '@{dataset.num_classes}'
  pretrained: True

preprocessor:
  name: base_preprocessor

trainer:
  name: train
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.0005
    num_epochs: 50
  scheduler:
    name: cosine_annealing
    T_max: 50
  loss: cross_entropy
  batch_size: 64
  
evaluation:
  name: base

recorder:
  name: base
  save_all: False